### ISSUE TITLE
Minimal information in README

### ISSUE THREAD

**Issue by ejball** [FacilityApi/tree-sitter-facility#2]
Can we add a sentence to the README indicating how this repository is being used?

**Comment by bryankenote** [comment]
Sure. [tree-sitter](https://tree-sitter.github.io/tree-sitter/) is a generic parser tool optimized for parsing buffers in a code editor. There are multiple applications that use tree-sitter parsers, even github. The structure of tree-sitter parser repository follows the standard structure.  So a tree-sitter parser repository speaks for itself. However, we can clarify in the README that this is currently being maintained for use with [Neovim](https://neovim.io/) for [highlights, indents, injections, and folds](https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/facility).
